/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helper.ExportBook;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Book;
import service.BookInterface;

/**
 *
 * @author Mhz
 */
public class BookForm extends javax.swing.JFrame {

    /**
     * Creates new form BookForm
     */
    public BookForm() {
        initComponents();
        clear();
    }
    public void clear(){
        if(titleTxt.getText().isEmpty() || authorTxt.getText().isEmpty() || publisherTxt.getText().isEmpty() || genreTxt.getText().isEmpty() || bookIdTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are already ", "Response", JOptionPane.INFORMATION_MESSAGE);
        }
        titleTxt.setText("");
        authorTxt.setText("");
        publisherTxt.setText("");
        genreTxt.setText("");
        bookIdTxt.setText("");
        bookIdSearchTxt.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        authorTxt = new javax.swing.JTextField();
        publisherTxt = new javax.swing.JTextField();
        genreTxt = new javax.swing.JTextField();
        bookIdTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bookIdSearchTxt = new javax.swing.JTextField();
        seacrhTxt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BOOK FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 72, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 208, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Author");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 265, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Publisher");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 327, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Genre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 394, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Book ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));
        getContentPane().add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 206, 216, -1));
        getContentPane().add(authorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 263, 216, -1));
        getContentPane().add(publisherTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 325, 216, -1));
        getContentPane().add(genreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 392, 216, -1));
        getContentPane().add(bookIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 216, -1));

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 100, -1));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 120, -1));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        deleteBtn.setText("Exit or Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Book ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 176, -1, 14));
        getContentPane().add(bookIdSearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 174, 150, -1));

        seacrhTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seacrhTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        seacrhTxt.setText("Search");
        seacrhTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seacrhTxtActionPerformed(evt);
            }
        });
        getContentPane().add(seacrhTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 167, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author", "Publisher", "Genre", "Book ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 239, 720, -1));

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        getContentPane().add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 690, 100, 35));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5153829.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel8ComponentShown(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (titleTxt.getText().isEmpty() || authorTxt.getText().isEmpty() || publisherTxt.getText().isEmpty() || genreTxt.getText().isEmpty() || bookIdTxt.getText().isEmpty()){
            int res = JOptionPane.showConfirmDialog(null, "Do you really want to close the Application", "Select", JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                System.exit(0);
            }
        } else {
            try {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
                BookInterface intr = (BookInterface) registry.lookup("book");
                Book book = new Book();
                book.setAuthor(authorTxt.getText());
                book.setBookId(bookIdTxt.getText());
                book.setPublisher(publisherTxt.getText());
                book.setGenre(genreTxt.getText());
                book.setTitle(titleTxt.getText());
                
                String response = intr.deleteBook(book);
                JOptionPane.showMessageDialog(this, "Delected Successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        /*
        */
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if(titleTxt.getText().isEmpty() || authorTxt.getText().isEmpty() || publisherTxt.getText().isEmpty() || genreTxt.getText().isEmpty() || bookIdTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kindly provide all book information", "Empty Fields!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
                BookInterface intr = (BookInterface) registry.lookup("book");
                Book book = new Book();
                book.setAuthor(authorTxt.getText());
                book.setBookId(bookIdTxt.getText());
                book.setPublisher(publisherTxt.getText());
                book.setGenre(genreTxt.getText());
                book.setTitle(titleTxt.getText());
                
                String response = intr.createBook(book);
                JOptionPane.showMessageDialog(this, "Successfully saved", "Success!", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
            BookInterface intr = (BookInterface) registry.lookup("book");
            ArrayList<Book> bookList = (ArrayList<Book>) intr.allBook();

            // Clear existing table data
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            // Populate the table with book data
            for (Book book : bookList) {
                Object[] rowData = {book.getTitle(), book.getAuthor(), book.getPublisher(), book.getGenre(), book.getBookId()};
                dtm.addRow(rowData);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String title = model.getValueAt(index, 0).toString();
        titleTxt.setText(title);
        String author = model.getValueAt(index, 1).toString();
        authorTxt.setText(author);
        String publisher = model.getValueAt(index, 2).toString();
        publisherTxt.setText(publisher);
        String genre = model.getValueAt(index, 3).toString();
        genreTxt.setText(genre);
        String bookId = model.getValueAt(index, 4).toString();
        bookIdTxt.setText(bookId);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(titleTxt.getText().isEmpty() || authorTxt.getText().isEmpty() || publisherTxt.getText().isEmpty() || genreTxt.getText().isEmpty() || bookIdTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kindly provide all book information", "Empty Fields!", JOptionPane.ERROR_MESSAGE);
        } else {
           try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
            BookInterface intrf = (BookInterface) registry.lookup("book");
            
            Book book = new Book();
            book.setAuthor(authorTxt.getText());
            book.setBookId(bookIdTxt.getText());
            book.setTitle(titleTxt.getText());
            book.setPublisher(publisherTxt.getText());
            book.setGenre(genreTxt.getText());
            
            String response = intrf.updateBook(book);
            JOptionPane.showMessageDialog(this, "Book updated Successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        } 
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
            BookInterface intrf = (BookInterface) registry.lookup("book");
            List<Book> bookList = intrf.allBook();
            ExportBook.exportToCSV(bookList);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void jLabel8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel8ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8ComponentShown

    private void seacrhTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seacrhTxtActionPerformed
        // TODO add your handling code here:
        if (bookIdSearchTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kindly provide the book Id", "Empty field!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
                BookInterface intrf = (BookInterface) registry.lookup("book");
                Book book = new Book();
                book.setBookId(bookIdSearchTxt.getText());
                book = intrf.getBookById(book);
                
                if (book == null) {
                    JOptionPane.showMessageDialog(null, "Record not found!",
                        "Response", JOptionPane.INFORMATION_MESSAGE);
            } else {
                    titleTxt.setText(book.getTitle());
                    authorTxt.setText(book.getAuthor());
                    publisherTxt.setText(book.getPublisher());
                    genreTxt.setText(book.getGenre());
                    bookIdTxt.setText(book.getBookId());
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_seacrhTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorTxt;
    private javax.swing.JTextField bookIdSearchTxt;
    private javax.swing.JTextField bookIdTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField genreTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField publisherTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton seacrhTxt;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
