/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helper.ExportUser;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.User;
import service.UserInterface;

/**
 *
 * @author Mhz
 */
public class UsersForm extends javax.swing.JFrame {
    private String password;

    public void clear() {
        emailTxt.setText("");
        useridSearchTxt.setText("");
        fullnamesTxt.setText("");
        passwordTxt.setText("");
        phoneNumberTxt.setText("");
    }
    public String emailPattern = "^[a-zA-Z0-9]+@[a-zA-Z0-9]+\\.[a-zA-Z0-9]+$";
    /**
     * Creates new form UsersForm
     */
    public UsersForm() {
        this.password = password;
        initComponents();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        useridSearchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fullnamesTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumberTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backHomeBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("User ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 74, -1, -1));
        getContentPane().add(useridSearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 72, 129, -1));

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 65, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fullnames");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 163, -1, -1));
        getContentPane().add(fullnamesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 161, 168, -1));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 498, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 243, -1, -1));

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 241, 168, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PhoneNumber");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 314, -1, -1));
        getContentPane().add(phoneNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 312, 168, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 404, -1, -1));
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 402, 168, -1));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 498, -1, -1));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 498, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Fullnames", "Email", "Phone NUmber", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 96, 670, -1));

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        getContentPane().add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1151, 557, -1, -1));

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 498, -1, -1));

        backHomeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backHomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-button.png"))); // NOI18N
        backHomeBtn.setText("Back Home");
        backHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backHomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 579, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5153829.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here
        if (useridSearchTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kindly provide user id", "Empty Field!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
                UserInterface intrf  = (UserInterface) registry.lookup("user");
                
                User user = new User();
                user.setUserId(useridSearchTxt.getText());
                user = intrf.getUserById(user);
                
                if (user == null) {
                    JOptionPane.showMessageDialog(null, "Record not found!",
                        "Response", JOptionPane.INFORMATION_MESSAGE);
            } else {
                    fullnamesTxt.setText(user.getFullnames());
                    emailTxt.setText(user.getEmail());
                    phoneNumberTxt.setText(user.getPhone_number());
                    passwordTxt.setText(user.getPassword());
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (fullnamesTxt.getText().isEmpty() || emailTxt.getText().isEmpty() || phoneNumberTxt.getText().isEmpty() || passwordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kindly fill out all the required fields!", "Empty Fields!", JOptionPane.ERROR_MESSAGE);
        } else if ( useridSearchTxt.getText().length() != 5) {
            JOptionPane.showMessageDialog(this, "The Id field must have 5 character", "Warring!", JOptionPane.WARNING_MESSAGE);
        } else if ( phoneNumberTxt.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "The phone number field must have 10 character", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (!(emailTxt.getText().matches(emailPattern))) {
            JOptionPane.showMessageDialog(this, "Enter a strong email", "Warring!", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
                UserInterface intrf = (UserInterface) registry.lookup("user");
                
                User user = new User();
                user.setEmail(emailTxt.getText());
                user.setFullnames(fullnamesTxt.getText());
                user.setPhone_number(phoneNumberTxt.getText());
                user.setUserId(useridSearchTxt.getText());
                
                String response = intrf.updateUser(user);
                JOptionPane.showMessageDialog(this, "User updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                clear();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (fullnamesTxt.getText().isEmpty() || emailTxt.getText().isEmpty() || phoneNumberTxt.getText().isEmpty() || passwordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kindly fill out all the required fields!", "Empty Fields!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
                UserInterface intrf = (UserInterface) registry.lookup("user");
                
                User user = new User();
                user.setEmail(emailTxt.getText());
                user.setFullnames(fullnamesTxt.getText());
                user.setPhone_number(phoneNumberTxt.getText());
                user.setUserId(useridSearchTxt.getText());
                
                String response = intrf.deleteUser(user);
                JOptionPane.showMessageDialog(this, "User deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                clear();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        if (fullnamesTxt.getText().isEmpty() || emailTxt.getText().isEmpty() || phoneNumberTxt.getText().isEmpty() || passwordTxt.getText().isEmpty()){
            int res = JOptionPane.showConfirmDialog(null, "Do you really want to close the Application", "Select", JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                System.exit(0);
            }
        }
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
            UserInterface intrf = (UserInterface) registry.lookup("user");
            List<User> userList = intrf.allUser();
            ExportUser.exportToCSV(userList);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_printBtnActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 81);
            UserInterface intr = (UserInterface) registry.lookup("user");
            ArrayList<User> userList = (ArrayList<User>) intr.allUser();

            // Clear existing table data
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            // Populate the table with book data
            for (User user : userList) {
                Object[] rowData = {user.getUserId(), user.getFullnames(), user.getEmail(), user.getPhone_number(), user.getPassword()};
                dtm.addRow(rowData);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        useridSearchTxt.setText(id);
        String name = model.getValueAt(index, 1).toString();
        fullnamesTxt.setText(name);
        String email = model.getValueAt(index, 2).toString();
        emailTxt.setText(email);
        String phone = model.getValueAt(index, 3).toString();
        phoneNumberTxt.setText(phone);
        String pass = model.getValueAt(index, 4).toString();
        passwordTxt.setText(pass);
    }//GEN-LAST:event_jTable1MouseClicked

    private void backHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeBtnActionPerformed
        // TODO add your handling code here:
        //new HomeForm(password).setVisible(true);
        new UsersForm().setVisible(false);
        
    }//GEN-LAST:event_backHomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHomeBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField fullnamesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField useridSearchTxt;
    // End of variables declaration//GEN-END:variables
}
